services:
  backend:
    build: 
      context: ./backend-springboot
      dockerfile: Dockerfile
    container_name: sign_lang_backend
    depends_on:
      - ai-service
    environment:
      - AI_SERVICE_URL=http://ai-service:8000
    ports:
      - "8080:8080"
    networks:
      - app-network
    restart: unless-stopped

  ai-service:
    build:
      context: ./ai-service-python
      dockerfile: Dockerfile
    container_name: sign_lang_ai
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - "8000:8000"
    networks:
      - app-network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend-react
      dockerfile: Dockerfile
      args:
        VITE_API_URL: http://localhost:8080
    container_name: sign_lang_frontend
    depends_on:
      - backend
    ports:
      - "80:80"
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
